name: yandex_music
description: "A powerlibrary for accessing Yandex Music API (api.music.yandex.net)."
version: 1.2.2
homepage: https://github.com/z3nsh0w/yandex_music_flutter

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  xml: ^6.5.0
  dio: ^5.9.0
  mime: ^2.0.0
  crypto: ^3.0.7


dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
  logger: ^2.6.1

flutter:
